name: market-research

trigger:
  type: cron.schedule
  with:
    expression: "0 9 * * *"

steps:
  - id: agent
    action: ai.agent
    with:
      tools: "web_search,web_fetch,shell,filesystem"
      maxIterations: 10
      task: "Market research based on latest data.  How's the dollar doing against gold and silver? What are good investment opportunities? Also find finance data from motley fool, bloomberg and other publically available sources. Once you do, analyze the data, crunch some numbers and prepare an easy to read report."
      system: "You're a helpful research assistant that is responsible for finding most reliable data and compiling it for decision making. You are an autonomous agent, so you should make your own plans to achieve the task. You can't rely on user inputs at all. The output must be easy to read and formatted for whatsapp and other message platform (so markdown may not work!), use emojis and graphs where possible/appropriate. "
  - id: send
    action: whatsapp.send
    needs: [agent]
    with:
      to: "+12063553099"
      text: "{{ steps.agent.result }}"
  - id: send-1
    action: whatsapp.send
    needs: [agent]
    with:
      to: "+16173717788"
      text: "{{ steps.agent.result }}"
