name: news-summarization-workflow

trigger:
  type: cron.schedule
  with:
    expression: "0 9 * * *"
    timezone: "America/los_angeles"

steps:
  - id: fetch-news
    action: http.get
    with:
      url: "https://news.google.com/rss"
      headers: "{}"
  - id: summarize-news
    action: ai.summarize
    needs: [fetch-news]
    with:
      text: "{{ steps.fetch-news.data }}"
      maxLength: 200
      style: "concise"
  - id: send-1
    action: whatsapp.send
    needs: [summarize-news]
    with:
      to: "+919096313716"
      text: "{{ steps.summarize-news.summary }}"
  - id: send-2
    action: whatsapp.send
    needs: [summarize-news]
    with:
      to: "+16173717788"
      text: "{{ steps.summarize-news.summary }}"
