name: daily-standup
description: Morning standup reminder

triggers:
  - type: cron.schedule
    config:
      expression: "0 9 * * 1-5"  # 9am weekdays
      timezone: America/New_York

steps:
  - id: send-reminder
    action: slack.post
    config:
      channel: "#team"
      text: |
        👋 Good morning team!

        Time for standup! Please share:
        • What did you work on yesterday?
        • What are you working on today?
        • Any blockers?

        React with ✅ when you've posted your update.
